### PR TITLE
Correct number of videos added.

### PR DESCRIPTION
**Pull request by JesperDramsch**
Changed the log to include the total number of videos found and how many could be added.

### CODE REVIEW

**Comment by dudemario** [comment]
Looks good, (that was my original intention but it slipped my mind), except the `Found videoIds.length videos` is unnecessary since I log it on [line 93](https://github.com/Elijas/auto-youtube-subscription-playlist-2/blob/better-error-handling/sheetScript.gs#L93)

**Comment by JesperDramsch** [comment]
Oh! I did not make that connection.

**Comment by dudemario** [comment]
What do you think of changing 
```
i -= j;
Logger.log("Added "+i+" videos to playlist. Error for "+j+" videos.")
```
to just
```
Logger.log("Added "+(videoIds.length - j)+" videos to playlist. Error for "+j+" videos.")
```
It's a bit clearer this way and i = videoIds.length anyways

**Comment by dudemario** [comment]
Also maybe change `j` to `errorCount` for clarity?

**Comment by dudemario** [comment]
Thanks for your help

**Comment by JesperDramsch** [comment]
Changing the variable is fine of course. I changed `i`, as I figured we might be able to use that later for successful additions, because you rightly pointed out it would be redundant with `videoIds.length`.

**Pull request merged**
