### PR TITLE
Timezone support

### PR DESCRIPTION
**Pull request by JesperDramsch**
Following the time shenanigans in #66 I implemented full timezone support.

Instead of UTC, GMT offset is used.

Adresses #35

### CODE REVIEW

**Comment by Fabian42** [comment]
Are you sure that you fully implemented timezones? https://www.youtube.com/watch?v=-5wpm-gesOY
(That's an entertaining video explaining the insanity of timezones, I recommend watching it just for fun, even if it might not be very helpful for this case.)

**Comment by JesperDramsch** [comment]
Never 😅

But we're getting the timezones from Google and passing them to google. What's the worst that can happen? *Nervous laugh*

**Comment by victorjzsun** [comment]
@JesperDramsch merged #66, please resolve conflict

**Comment by victorjzsun** [comment]
@JesperDramsch close this since you have an updated PR?

**Comment by JesperDramsch** [comment]
They're different PRs though.

Victor Sun <notifications@github.com> schrieb am Mi., 22. Apr. 2020, 20:17:

**Comment by victorjzsun** [comment]
Ok, just one comment then: https://github.com/Elijas/auto-youtube-subscription-playlist-2/pull/72#discussion_r413245303

**Comment by JesperDramsch** [comment]
@victorjzsun ok

**Comment by victorjzsun** [comment]
https://github.com/Elijas/auto-youtube-subscription-playlist-2/pull/72#discussion_r413245303 references the issue of changing the timezone within the script settings

**Comment by JesperDramsch** [comment]
Thanks for the screengrab. Added it to the readme

**Pull request merged**
